### ISSUE TITLE
command line client does not run for ofximport

### ISSUE THREAD

**Issue by chbndrhnns** [rienafairefr/pynYNAB#45]
Running `pynYNAB ofximport` gives me

```
pynynab ofximport
Traceback (most recent call last):
  File "/Users/jo/.virtualenvs/m2ynab/bin/pynynab", line 11, in <module>
    load_entry_point('pynYNAB===dev', 'console_scripts', 'pynynab')()
  File "/Users/jo/.virtualenvs/m2ynab/lib/python2.7/site-packages/pynYNAB-dev-py2.7.egg/pynYNAB/__main__.py", line 128, in main
    MainCommands()
  File "/Users/jo/.virtualenvs/m2ynab/lib/python2.7/site-packages/pynYNAB-dev-py2.7.egg/pynYNAB/__main__.py", line 59, in __init__
    if args.password is None:
AttributeError: 'Namespace' object has no attribute 'password'
```

**Comment by rienafairefr** [comment]
Sorry, the command line scripts havent been as updated as the rest. 

Are you calling the ofximport with a --password argument or a config file with a password element ? What's the output of `pynYNAB ofximport --help` ?

**Comment by chbndrhnns** [comment]
The same error message as before.

**Comment by rienafairefr** [comment]
I just pushed a commit, 07dea45feed6f57a64c24d0b8525ffc9fa2882d2 try it out if it solves your problem.

**Comment by chbndrhnns** [comment]
Fixed.
