### ISSUE TITLE
pynYNAB ofximport issue

### ISSUE THREAD

**Issue by scottrobertson** [rienafairefr/pynYNAB#54]
```
pynYNAB ofximport --help
Traceback (most recent call last):
  File "/usr/local/bin/pynYNAB", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/pynYNAB/__main__.py", line 128, in main
    MainCommands()
  File "/usr/local/lib/python2.7/site-packages/pynYNAB/__main__.py", line 59, in __init__
    if args.password is None:
AttributeError: 'Namespace' object has no attribute 'password'
```

Same issue as #45. So i ran:

```
pip install git+git://github.com/rienafairefr/pynYNAB.git@master
```

And now i get:

```
Traceback (most recent call last):
  File "/usr/local/bin/pynYNAB", line 11, in <module>
    load_entry_point('pynYNAB===dev', 'console_scripts', 'pynynab')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named __main__
```

**Comment by scottrobertson** [comment]
Could this just be a case of needing to update the published binary? It's potentially just an old version.

**Comment by rienafairefr** [comment]
I think that was just a case of a reffactor that missed a small reference, the scripts main entry point is at  pynYNAB.scripts.__main__, this should fix the problem for the github master install. 

I'll update the pypi to the latest

**Comment by rienafairefr** [comment]
you might have an old version installed shadowing stuff on your machine as well, not sure
