### ISSUE TITLE
nYnabClient constructor raises Exception

### ISSUE THREAD

**Issue by bdabelow** [rienafairefr/pynYNAB#63]
```
$ uname -a
Linux 4.13.0-31-generic #34-Ubuntu SMP Fri Jan 19 16:34:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ python -V
Python 3.6.3
```

It looks like nYnabClient.\_\_init\_\_ was not adapted for the new interface of create_client in ClientFactory.

```
Traceback (most recent call last):
  File "ynab.py", line 11, in <module>
    client = nYnabClient(email=config["ynab"]["email"], password=config["ynab"]["password"], budgetname=config["ynab"]["budget_name"])
  File "/home/benjamin/Data/Computer/Python_Projects/bfin/venv/lib/python3.6/site-packages/pynYNAB/Client.py", line 21, in __new__
    return factory.create_client(passed)
  File "/home/benjamin/Data/Computer/Python_Projects/bfin/venv/lib/python3.6/site-packages/pynYNAB/ClientFactory.py",line 55, in create_client
    raise NoBudgetNameException
pynYNAB.exceptions.NoBudgetNameException: you should pass a budget_name
```

**Comment by apfelmus123** [comment]
Do you have a workaround until it is included?

**Comment by rienafairefr** [comment]
Sorry for taking that long coming back to your issue.

You can use the clientfactory directly, I think, nYnabClientFactory().create_client(email, password, budget_name, connection)  

I'm working on your PR (rebasing on new commits where I'm fixing the unittests for PRs), should be integrated soon

**Comment by bdabelow** [comment]
PR has been merged long ago.
